(ns sample.gridlist
  "Faithful port of https://docs.flutter.dev/cookbook/lists/grid-lists"
  (:require
   ["package:flutter/material.dart" :as m]
   [cljd.flutter :as f]))

(defn main []
  (let [title "Grid List"]
    (m/runApp
     (f/widget
      (m/MaterialApp .title title)
      .home
      (m/Scaffold .appBar (m/AppBar .title (m/Text title)))
      .body
      :get {{{:flds [displaySmall]} .-textTheme} m/Theme}
      (m/GridView.count .crossAxisCount 2)
      .children
      (for [i (range 100)]
        (m/Center .child (m/Text (str "Item " i) .style displaySmall)))))))
